onehundreddaysofcode/onehundreddaysofcode/stoltzmaniac/__init__.py
# -*- coding: utf-8 -*-
"""The stoltzmaniac module"""
from . import views  # noqa

onehundreddaysofcode/onehundreddaysofcode/stoltzmaniac/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
import pandas as pd
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    jsonify,
    session,
)
from flask_login import login_required

from onehundreddaysofcode.database import mdb
from onehundreddaysofcode.utils import flash_errors, twtr
from onehundreddaysofcode.twitter.mongo_forms import TwitterForm
from onehundreddaysofcode.twitter.utils import twitter_search
from onehundreddaysofcode.stoltzmaniac.utils import analyze_tweet_sentiment, analyze_csv, altair_plot


blueprint = Blueprint(
    "stoltzmaniac", __name__, url_prefix="/stoltzmaniac", static_folder="../static"
)


@blueprint.route("/")
def home():
    return render_template("stoltzmaniac/home.html")


@blueprint.route("/csv_example")
def csv_example():
    data = analyze_csv()
    return data.to_html()


@blueprint.route("/altair_example")
def altair_example():
    plot = altair_plot()
    return render_template("stoltzmaniac/altair_plot.html", plot=plot.to_html())


@blueprint.route("/twitter", methods=["GET", "POST"])
@login_required
def twitter_sentiment():
    form = TwitterForm(request.form)
    if request.method == "GET":
        return render_template(
            "stoltzmaniac/twitter_sentiment.html", myform=form
        )

    elif request.method == "POST" and form.validate_on_submit():
        chart_data = []
        data = twitter_search(request)
        sentiment = analyze_tweet_sentiment(data)
        return render_template(
            "stoltzmaniac/twitter_sentiment.html", myform=form,
            chart_data=sentiment[1], tweets=sentiment[0]
        )

onehundreddaysofcode/onehundreddaysofcode/templates/stoltzmaniac/altair_plot.html
{% extends "layout.html" %}

{% block content %}
<!-- Load c3.css -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.css" rel="stylesheet">

<!-- Load d3.js and c3.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.js"></script>

<div class="container">
    <h1 class="mt-5">Stoltzmaniac - Altair Histogram Example</h1>

        <strong>Plotting Example</strong>
        <div>
            {{ plot | safe }}>
        </div>
</div>
{% endblock %}

onehundreddaysofcode/onehundreddaysofcode/templates/stoltzmaniac/home.html
{% extends "layout.html" %}

{% block content %}
<!-- Load c3.css -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.css" rel="stylesheet">

<!-- Load d3.js and c3.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.js"></script>

    <div class="container">
        <h2>Stoltzmaniac Projects</h2>
        <hr>

      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="{{ url_for('stoltzmaniac.csv_example') }}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://i.stack.imgur.com/BLE2H.jpg" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Download and display CSV table</h3>
          <p>A simple piece of code that downloads a CSV from a URL and displays it as an html table.</p>
          <a class="btn btn-primary" href="{{ url_for('stoltzmaniac.csv_example') }}">View Project
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Two -->
      <div class="row">
        <div class="col-md-7">
          <a href="{{ url_for('stoltzmaniac.altair_example') }}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://i.stack.imgur.com/4HXGr.png" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Plotting data with altair</h3>
          <p>An example of how easy it is to plot data with a Python library (altair) and display it on a page.</p>
          <a class="btn btn-primary" href="{{ url_for('stoltzmaniac.altair_example') }}">View Project
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Three -->
      <div class="row">
        <div class="col-md-7">
          <a href="{{ url_for('stoltzmaniac.twitter_sentiment') }}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://cdn-images-1.medium.com/max/1200/1*EvfJW_CcF1u27ZMyt280hg.png" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Sentiment Analysis on Twitter</h3>
          <p>Pick a search term and your data will be given a sentiment rating!</p>
          <a class="btn btn-primary" href="{{ url_for('stoltzmaniac.twitter_sentiment') }}">View Project
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div>
      <!-- /.row -->
      <hr>
    </div>
    <!-- /.container -->

{% endblock %}

onehundreddaysofcode/onehundreddaysofcode/templates/stoltzmaniac/twitter_sentiment.html
{% extends "layout.html" %}

{% block content %}
<!-- Load c3.css -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.css" rel="stylesheet">

<!-- Load d3.js and c3.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.12/c3.js"></script>

<div class="container">
    <h1 class="mt-5">Stoltzmaniac - Twitter Sentiment Analysis</h1>

    <form id="randomDataForm" class="form" method="POST" action="" role="form">
        {{ myform.csrf_token }}
        <div class="form-group">
            {{ myform.search_term.label }}
            {{ myform.search_term(placeholder="Search Term, Username, or Hashtag", class_="form-control")}}
        </div>
        <div class="form-group">
            {{ myform.count.label }}
            {{ myform.count(placeholder="# of results requested", class_="form-control")}}
        </div>
        <p><input class="btn btn-primary" type="submit" value="Submit"></p>
    </form>

    {% if chart_data %}
        <strong>Sentiment of tweets:</strong>

        {{ chart_data }}

        <br/>

        <ul>
            {% for tweet in tweets %}
                <li>{{ tweet }}</li>
            {% endfor %}
        </ul>

    {% endif %}


</div>
{% endblock %}